export const ProductActions = {
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  GET_ALL_PRODUCTS_FROM_CATEGORY: "GET_ALL_PRODUCTS_FROM_CATEGORY",
  DELETE_ALL_PRODUCTS: "DELETE_ALL_PRODUCTS",
  DELETE_ALL_PRODUCTS_FROM_CATEGORY: "DELETE_ALL_PRODUCTS_FROM_CATEGORY",
  CHANGE_PRODUCT_VALUE: "CHANGE_PRODUCT_VALUE",
}
